/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e1e7ff',
        'surface-container-highest': '#dae2fc',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434654',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#737685',
        'outline-variant': '#c3c6d6',
        'surface-tint': '#1b55d0',
        primary: '#003594',
        'on-primary': '#ffffff',
        'primary-container': '#004ac6',
        'on-primary-container': '#b8c8ff',
        'inverse-primary': '#b4c5ff',
        secondary: '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#9af1c6',
        'on-secondary-container': '#0b714e',
        tertiary: '#682c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8c3d00',
        'on-tertiary-container': '#ffba94',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed': '#9df4c9',
        'secondary-fixed-dim': '#81d8ae',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005237',
        'tertiary-fixed': '#ffdbca',
        'tertiary-fixed-dim': '#ffb68e',
        'on-tertiary-fixed': '#331200',
        'on-tertiary-fixed-variant': '#763300',
        background: '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fc',
        'subject-maths': '#004ac6',
        'subject-science': '#006c4a',
        'subject-social': '#8c3d00',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
