/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface) / <alpha-value>)',
        outline: 'rgb(var(--outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'surface-tint': 'rgb(var(--surface-tint) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'inverse-primary': '#b4c5ff',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        'on-secondary': '#ffffff',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        tertiary: '#682c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8c3d00',
        'on-tertiary-container': '#ffba94',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed': '#9df4c9',
        'secondary-fixed-dim': '#81d8ae',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005237',
        'tertiary-fixed': '#ffdbca',
        'tertiary-fixed-dim': '#ffb68e',
        'on-tertiary-fixed': '#331200',
        'on-tertiary-fixed-variant': '#763300',
        background: 'rgb(var(--background) / <alpha-value>)',
        'on-background': 'rgb(var(--on-background) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'subject-maths': '#004ac6',
        'subject-science': '#006c4a',
        'subject-social': '#8c3d00',
        // Also expose raw palette scales directly for utility use
        lavender: {
          50: "#ecedf8",
          100: "#dadcf1",
          200: "#b5b8e3",
          300: "#8f95d6",
          400: "#6a72c8",
          500: "#454fba",
          600: "#373f95",
          700: "#292f70",
          800: "#1c1f4a",
          900: "#0e1025",
          950: "#0a0b1a"
        },
        'pale-slate': {
          50: "#f1f2f4",
          100: "#e3e4e8",
          200: "#c6c9d2",
          300: "#aaaebb",
          400: "#8e93a4",
          500: "#71788e",
          600: "#5b6071",
          700: "#444855",
          800: "#2d3039",
          900: "#17181c",
          950: "#101114"
        },
        'dark-slate-grey': {
          50: "#eff4f5",
          100: "#e0eaeb",
          200: "#c1d5d7",
          300: "#a2bfc3",
          400: "#83aaaf",
          500: "#63959c",
          600: "#50777c",
          700: "#3c595d",
          800: "#283c3e",
          900: "#141e1f",
          950: "#0e1516"
        },
        'dark-teal': {
          50: "#e9f7fc",
          100: "#d3eff8",
          200: "#a7dff1",
          300: "#7bceea",
          400: "#4fbee3",
          500: "#22aedd",
          600: "#1c8bb0",
          700: "#156884",
          800: "#0e4658",
          900: "#07232c",
          950: "#05181f"
        }
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
